language: node_js
node_js:
- 6
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
sudo: false
deploy:
  provider: npm
  email: cem.moreau@gmail.com
  on:
    repo: duniter/duniter-ui
    tags: true
  api_key:
    secure: pKMmSDM7aspIBaT5cW16+4Ov3AaJh6bEA+laKW5Ci6P+VZi50UdYtjMi4Yuag2NvYmQN9uIljFA9fBfYMk8twNG4FuG22++Yp/xboQAtMGo6NtEWeBZ1vbyepY377anXHrHz+ePR5NO2n+221VaV9QmFvVKiEMnuJzWuF5BlhX/ShxZjHX7RQZU9InpR+jsLxiAxOj7fMKsXL+JYFXRZx9pEuMqhqFeFbEn543Ss57+cJGttZVAjKTptplD4ZEA+WovYbv5PU1AQ3157MFzNSUd+mDnfwqlvdQuMldSiGsNRcK8EWbG52UjLEThTvs0ag4PlRbYPjMDiIdq7zOCWvwwcb6cRuUkC0wsK5YDJEUXkIfi/aVMNjFMm1HZRnOOenna83eKl8tLbkBdkhWtKl3wwG+VJsLxP7AYoK5mqN5kECfNw9w9AA7Oovk9bOp8/pxRZmnkHmWVWFXcaY8UikYEtWtrZQi7aG0MpRKJGUPrJmw9FGqEftTSzQuZ5EQQYrZXjXHO7j0iWB5AFNM5Wyb3HVjmccQupemm+9aZVP6dwLbzH/SKDkDsMVf+rByasrrM59rg6KMVW+XOXoYp9b7RUDUs/LjT/PrgehEk+MPJf/XBS5RBEdKhNxcDZ4NErKgVN7ZbYErkjOfQqkw6aJEIkZEE2ZQINa3LqvkY4PdA=
